# organization name, it's used to get github repo url, also in page title
name: alibaba

# badge style, can be "flat", "flat-square" or ""
# see http://shields.io/ for details
badge_style: flat-square

# meta headers in html
title:       alibaba
description: alibaba Node.js modules list
keywords:    alibaba, nodejs, Node.js, node, node-modules, node_modules

# list of projects, this will be sorted by name;
# every package is either string or object
projects:
 - hbase-client:
    repo: alibaba/node-hbase-client
 - ots
 - ali-oss
 - node-query:
    repo: alibaba/nquery
 - top

# list of maintainers, this won't be sorted
maintainers:
 - name:    fengmk2
   github:  fengmk2   # github account, required: we link to it
   npm:     fengmk2   # npm account, required to determine lead maintainer
   twitter: fengmk2 # twitter account, optional
   gittip:  fengmk2   # gittub badge, optional
   email:   fengmk2@gmail.com

 - name:    Yiyu He
   github:  dead-horse
   npm:     dead_horse
   twitter: deadhorse_busi
   gittip:  dead-horse
   email:   heyiyu.deadhorse@gmail.com

 - name:    fool2fish
   github:  fool2fish
   npm:     fool2fish
   twitter: fool2fish
   gittip:  fool2fish
   email:   fool2fish@gmail.com

 - name:    coolme200
   github:  coolme200
   npm:     coolme200
   twitter: coolme200
   gittip:  coolme200
   email:   2001-wms@163.com

 - name:    windyrobin
   github:  windyrobin
   npm:     windyrobin
   twitter: windyrobin
   gittip:  windyrobin
   email:   windyrobin@gmail.com

# this determines what info will be fetched with `make db`;
# you can comment out stuff to reduce number of http requests
db.json:
  projects:
   - node        # node version, it's the lowest version from .travis.yml
   - description # package description from package.json (from npm registry)
   - maintainer  # maintainer npm account (= _npmUser of last published ver)
  maintainers:
   - packages    # amount of packages this npm user has
